# ===== TAXONOMY =====
TASKS = [
    "text-classification","token-classification","question-answering",
    "translation","summarization","text-generation","fill-mask",
    "table-question-answering","image-classification","object-detection",
    "image-segmentation","image-to-text","text-to-image","speech-recognition",
    "audio-classification","text-to-speech","reinforcement-learning",
    "time-series-forecasting","tabular-classification","tabular-regression",
    "agent","document-question-answering","sentence-similarity",
    "zero-shot-classification","optical-character-recognition","pose-detection",
    "depth-estimation","video-classification","semantic-segmentation",
    "super-resolution","image-enhancement","anomaly-detection"
]
DATA_TYPES = {
    "nlp": ["text-classification","summarization","question-answering","translation","text-generation","fill-mask"],
    "vision": ["image-classification","object-detection","image-segmentation","depth-estimation","pose-detection","super-resolution"],
    "audio": ["speech-recognition","audio-classification","text-to-speech"],
    "multimodal": ["image-to-text","text-to-image","video-classification"],
    "tabular": ["tabular-regression","tabular-classification","time-series-forecasting"],
    "agentic": ["agent","reinforcement-learning","anomaly-detection"]
}
CATEGORIES = {
    "finance": ["time-series-forecasting","tabular-regression","tabular-classification","text-classification","anomaly-detection"],
    "healthcare": ["image-segmentation","image-classification","token-classification","question-answering","anomaly-detection"],
    "engineering": ["object-detection","image-segmentation","time-series-forecasting","depth-estimation","pose-detection"],
    "education": ["translation","summarization","question-answering","sentence-similarity"],
    "llms": ["text-generation","fill-mask","agent","zero-shot-classification"],
    "science": ["time-series-forecasting","super-resolution","image-enhancement","anomaly-detection"],
    "geospatial": ["image-segmentation","object-detection","depth-estimation"],
    "agriculture": ["image-classification","object-detection","time-series-forecasting"],
    "manufacturing": ["anomaly-detection","time-series-forecasting","tabular-classification"],
    "energy": ["time-series-forecasting","anomaly-detection","reinforcement-learning"],
    "climate": ["time-series-forecasting","image-segmentation","super-resolution"],
    "transportation": ["object-detection","reinforcement-learning","anomaly-detection"],
    "law": ["text-classification","summarization","question-answering"],
    "marketing": ["text-classification","summarization","sentiment-analysis","zero-shot-classification"],
    "news": ["summarization","text-classification","question-answering"],
    "retail": ["tabular-regression","tabular-classification","anomaly-detection"],
    "sports": ["time-series-forecasting","video-classification","pose-detection"],
    "art": ["text-to-image","image-enhancement","image-generation"],
    "robotics": ["reinforcement-learning","pose-detection","object-detection"],
    "security": ["anomaly-detection","audio-classification","object-detection","speech-recognition"],
    "gaming": ["reinforcement-learning","agent","text-to-image","text-generation"],
    "multilingual": ["translation","zero-shot-classification","summarization"],
    "satellite": ["image-segmentation","object-detection","depth-estimation"],
    "chemistry": ["tabular-regression","time-series-forecasting","anomaly-detection"],
    "biology": ["image-segmentation","anomaly-detection","tabular-regression"],
    "astronomy": ["image-segmentation","super-resolution","time-series-forecasting"],
    "psychology": ["text-classification","question-answering","speech-recognition"],
    "sociology": ["text-classification","summarization","translation"],
    "music": ["audio-classification","text-to-speech","speech-recognition"],
    "film": ["video-classification","text-to-image","summarization"],
    "fashion": ["image-classification","image-generation","anomaly-detection"],
    "construction": ["object-detection","depth-estimation","anomaly-detection"],
    "urban-planning": ["image-segmentation","object-detection","super-resolution"],
    "insurance": ["tabular-regression","anomaly-detection","text-classification"],
    "real-estate": ["tabular-regression","image-classification","summarization"],
    "space": ["super-resolution","time-series-forecasting","object-detection"],
    "social-media": ["text-classification","sentiment-analysis","agent"],
    "crypto": ["time-series-forecasting","anomaly-detection","tabular-regression"],
    "startup": ["text-classification","summarization","agent","time-series-forecasting"],
    "ethics": ["text-classification","question-answering","agent"],
    "policy": ["question-answering","summarization","translation"]
}